spring:
  application:
    name: url-shortening-service
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/url_shortener}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:postgres}
  jpa:
    open-in-view: false
  liquibase:
    change-log: classpath:db/changelog/master.yaml
logging:
  level:
    root: INFO

---
spring:
  config:
    activate:
      on-profile: develop
  datasource:
    url: jdbc:postgresql://db:5432/url_shortener
    username: postgres
    password: postgres
